#!/bin/sh
#
# Startup script for serverz3950
#
# chkconfig: 2345 50 50
#
### BEGIN INIT INFO
# Provides: loolmonitor
# Required-Start:	$network $local_fs
# Required-Stop:	$network $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Starts loolmonitor
# Description: start the loolmonitor
# processname: python3.6 -m loolmonitor
### END INIT INFO

# Source function library.
. /etc/init.d/functions

case "$1" in
start)
    echo -n "Starting $0 services: "
    if [ ! -d /var/log/loolmonitor ]
    then
        mkdir /var/log/loolmonitor
    fi
    cd /opt/monitor || exit 1
    python3.6 -m loolmonitor -w https://alfresco.arawa.fr/alfresco/s/ -u admin -p arawa098 </dev/null >/var/log/loolmonitor/loolmonitor.log 2>&1 & disown
    ;;
stop)
    echo -n "Stopping $0 services: "
    pkill -f "python3.6 -m loolmonitor"
    ;;
status)
    n=$(pgrep -cf "python3.6 -m loolmonitor")
    if [ "$n" -lt 3 ]; then
	echo >&2 'KO'
    else
	echo >&2 "OK: $n loolmonitor"
	echo >&2 `pgrep -fl "python3.6 -m loolmonitor"`
    fi
    ;;
restart|reload|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
condrestart)
    $0 status
    if [ $? -eq 0 ]; then
      $0 stop
      $0 start
    fi
    ;;
*)
    echo $"Usage: $0 {start|stop|status|restart|reload|force-reload}"
    exit 1
esac
exit 0
